name: 🚀 Deploy via Hostinger FTP

on:
  push:
    branches:
      - main   # change if you use another branch (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "APP_ENV=production" > mkt/.env
          echo "SQL_DSN=${{ secrets.SQL_DSN }}" >> mkt/.env
          echo "SQL_USER=${{ secrets.SQL_USER }}" >> mkt/.env
          echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> mkt/.env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> mkt/.env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> mkt/.env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> mkt/.env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> mkt/.env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> mkt/.env
          echo "FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}" >> mkt/.env

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./mkt   # upload this folder
          server-dir: /platform   # remote path
          dangerous-clean-slate: false
